### ISSUE TITLE
not working when runing test.

### ISSUE THREAD

**Issue by Vikram1234567** [wwwwwwwwwwwwwwwwwwwwwwwwwwwwww/m.io#8]
uh here is what I get. Please help

> m.io@0.0.1 test /app
> node tests/test.js

internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module 'uws'
Require stack:
- /app/src/GameServer.js
- /app/tests/test.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/app/src/GameServer.js:2:11)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/src/GameServer.js', '/app/tests/test.js' ]
}
npm ERR! Test failed.  See above for more details.

**Comment by ChickenPleb** [comment]
same here

**Comment by Name9010** [comment]
try write terminal or console : "npm i uws"

**Comment by Star2sLMAO** [comment]
did that, nothing worked
